name = "Conflux"
uuid = "2703a059-2ab6-41ff-bfd0-de7e7f183509"
authors = ["Anton Oresten <anton.oresten42@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
